export const CART_ACTIONS_CONSTANT = {
  CART_HIDDEN: 'CART_HIDDEN',
  ADD_ITEM_FROM_CART: 'ADD_ITEM',
  DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
  REMOVE_ALL_ITEM_FROM_CART: 'REMOVE_ALL_ITEM_FROM_CART',
};
